use_gpu: True
device: 7
seed: 12345
outdir: exp
federate:
  mode: standalone
  method: fedavg
#  total_round_num: 100
  client_num: 20
  make_global_train: True
  make_global_eval: True
  pl_save_to: ckpt
data:
  type: pl_data
  dataset_name: cb
  batch_size: 16
  max_seq_len: 128
  num_workers: 0
model:
  type: pl_model
  model_type: bert-large-cased
  freeze_param: ['model']
trainer:
  type: pl_trainer
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    type: AdamW
#    lr: 5e-3
    weight_decay: 0.01
  scheduler:
    type: step
    warmup_ratio: 0.1
