client_1:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.05
    grad_clip: 5.0
  federate:
    local_update_steps: 50
client_2:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 20
client_3:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 20
client_4:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 20
client_5:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 20
client_6:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 10
client_7:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 1
client_8:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.0001
  federate:
    local_update_steps: 1
client_9:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 1
client_10:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 1
client_11:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 5
client_12:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 14
client_13:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 14
client_14:
  model:
    out_channels: 12
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 675
client_15:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 832
client_16:
  model:
    out_channels: 19
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 431