use_gpu: False

device: 0

backend: torch

federate:
  mode: standalone
  client_num: 2
model:
  type: lr
  use_bias: False

data:
  root: data/
  type: abalone
  batch_size: 4000
  splits: [0.8, 0.2]

  
dataloader:
  # Type of sampler
  type: raw
 # batch_size: 2000
 

criterion:
  type: Regression
trainer:
  type: none    
train:
  optimizer:
    bin_num: 1000
    lambda_: 10
    gamma: 0
    num_of_trees: 5
    max_tree_depth: 3
xgb_base:
  use: True
  key_size: 256
  dims: [4, 8]

eval:
  freq: 5
  best_res_update_round_wise_key: test_loss