use_gpu: True
device: 1
early_stop:
  patience: 100000
seed: 2333
federate:
  mode: standalone
  local_update_steps: 5
  total_round_num: 1000
  sample_client_rate: 0.1
  client_num: 200
  batch_or_epoch: epoch
data:
  root: data/
  type: femnist
  # form: dataloader
  splits: [0.6,0.2,0.2]
  batch_size: 50
  subsample: 0.05
  num_workers: 0
  # transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
  transform: [['ToTensor']]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
optimizer:
  lr: 0.01
  weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct', 'poison_attack_acc']
  # split: ['test']
attack:
  setting: 'all'
  freq: 10
  attack_method: 'backdoor'
  attacker_id: -1
  label_type: 'dirty'
  trigger_type: edge
  target_label_ind: 1
  scale_poisoning: False
  scale_para: 5.0
  mean: [0.1307]
  std: [0.3081]
