use_gpu: True
device: 2
early_stop:
  patience: 10000
seed: 2333
federate:
  mode: standalone
  local_update_steps: 3
  batch_or_epoch: epoch
  total_round_num: 1000
  sample_client_rate: 0.1
  # unseen_clients_rate: 0.2
  client_num: 100
data:
  root: data/
  type: 'CIFAR10@torchvision'
  splits: [1.0, 0.0, 0.0]
  batch_size: 32
  num_workers: 0
  transform: [['ToTensor']]
  args: [{'download': True}]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]
model:
  type: resnet18
  hidden: 512
  out_channels: 10
  dropout: 0.0
optimizer:
  lr: 0.01
  weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  # split: ['test']
  metrics: ['acc', 'correct', 'poison_attack_acc']
attack:
  setting: 'fix'
  freq: 10
  attack_method: 'backdoor'
  attacker_id: -1
  label_type: 'dirty'
  trigger_type: edge
  target_label_ind: 9
  scale_poisoning: False
  scale_para: 5.0
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

