use_gpu: True
device: 0
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  total_round_num: 1000
  sample_client_num: 20
  client_num: 10
data:
  root:  data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 10
  subsample: 0.001
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
train:
  local_update_steps: 50
  optimizer:
    lr: 0.01
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
attack:
  attack_method: gan_attack
  target_label_ind: 3
  attacker_id: 5