use_gpu: True
device: 0
seed: 12345
federate:
  mode: standalone
  total_round_num: 10
  sample_client_num: 5
  client_num: 10
data:
  root: data/
  type: toy
  splits: [0.6,0.2,0.2]
  batch_size: 1
  subsample: 0.0001
  num_workers: 0
model:
  type: lr
  hidden: 2048
  out_channels: 62
train:
  local_update_steps: 2
  optimizer:
    lr: 0.01
    weight_decay: 0.0
trainer:
  type: general
eval:
  freq: 10
  metrics: ['acc', 'correct']
attack:
  attack_method: PassivePIA
  classifier_PIA: svm