use_gpu: True
device: 0
<<<<<<< HEAD
early_stopping: 1000
=======
early_stop:
  patience: 100
>>>>>>> be synchronized with gitlab
seed: 12345
federate:
  mode: standalone
  local_update_steps: 1
  total_round_num: 1000
  sample_client_num: 10
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 1
  subsample: 0.0001
  num_workers: 0
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
optimizer:
  lr: 0.01
  weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
attack:
  attack_method: DLG
  max_ite: 500
  reconstruct_lr: 0.1


