# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC_comm_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17gRPC_comm_manager.proto\"n\n\x0eMessageRequest\x12%\n\x03msg\x18\x01 \x03(\x0b\x32\x18.MessageRequest.MsgEntry\x1a\x35\n\x08MsgEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.MsgValue:\x02\x38\x01\"j\n\x08MsgValue\x12\x1e\n\nsingle_msg\x18\x01 \x01(\x0b\x32\x08.mSingleH\x00\x12\x1a\n\x08list_msg\x18\x02 \x01(\x0b\x32\x06.mListH\x00\x12\x1a\n\x08\x64ict_msg\x18\x03 \x01(\x0b\x32\x06.mDictH\x00\x42\x06\n\x04type\"R\n\x07mSingle\x12\x15\n\x0b\x66loat_value\x18\x01 \x01(\x02H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x13\n\tstr_value\x18\x03 \x01(\tH\x00\x42\x06\n\x04type\"&\n\x05mList\x12\x1d\n\nlist_value\x18\x01 \x03(\x0b\x32\t.MsgValue\"o\n\x05mDict\x12)\n\ndict_value\x18\x01 \x03(\x0b\x32\x15.mDict.DictValueEntry\x1a;\n\x0e\x44ictValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.MsgValue:\x02\x38\x01\"\x1e\n\x0fMessageResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2D\n\x10gRPCComServeFunc\x12\x30\n\x0bsendMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponseb\x06proto3'
)

_MESSAGEREQUEST = DESCRIPTOR.message_types_by_name['MessageRequest']
_MESSAGEREQUEST_MSGENTRY = _MESSAGEREQUEST.nested_types_by_name['MsgEntry']
_MSGVALUE = DESCRIPTOR.message_types_by_name['MsgValue']
_MSINGLE = DESCRIPTOR.message_types_by_name['mSingle']
_MLIST = DESCRIPTOR.message_types_by_name['mList']
_MDICT = DESCRIPTOR.message_types_by_name['mDict']
_MDICT_DICTVALUEENTRY = _MDICT.nested_types_by_name['DictValueEntry']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
MessageRequest = _reflection.GeneratedProtocolMessageType(
    'MessageRequest',
    (_message.Message, ),
    {
        'MsgEntry': _reflection.GeneratedProtocolMessageType(
            'MsgEntry',
            (_message.Message, ),
            {
                'DESCRIPTOR': _MESSAGEREQUEST_MSGENTRY,
                '__module__': 'gRPC_comm_manager_pb2'
                # @@protoc_insertion_point(class_scope:MessageRequest.MsgEntry)
            }),
        'DESCRIPTOR': _MESSAGEREQUEST,
        '__module__': 'gRPC_comm_manager_pb2'
        # @@protoc_insertion_point(class_scope:MessageRequest)
    })
_sym_db.RegisterMessage(MessageRequest)
_sym_db.RegisterMessage(MessageRequest.MsgEntry)

MsgValue = _reflection.GeneratedProtocolMessageType(
    'MsgValue',
    (_message.Message, ),
    {
        'DESCRIPTOR': _MSGVALUE,
        '__module__': 'gRPC_comm_manager_pb2'
        # @@protoc_insertion_point(class_scope:MsgValue)
    })
_sym_db.RegisterMessage(MsgValue)

mSingle = _reflection.GeneratedProtocolMessageType(
    'mSingle',
    (_message.Message, ),
    {
        'DESCRIPTOR': _MSINGLE,
        '__module__': 'gRPC_comm_manager_pb2'
        # @@protoc_insertion_point(class_scope:mSingle)
    })
_sym_db.RegisterMessage(mSingle)

mList = _reflection.GeneratedProtocolMessageType(
    'mList',
    (_message.Message, ),
    {
        'DESCRIPTOR': _MLIST,
        '__module__': 'gRPC_comm_manager_pb2'
        # @@protoc_insertion_point(class_scope:mList)
    })
_sym_db.RegisterMessage(mList)

mDict = _reflection.GeneratedProtocolMessageType(
    'mDict',
    (_message.Message, ),
    {
        'DictValueEntry': _reflection.GeneratedProtocolMessageType(
            'DictValueEntry',
            (_message.Message, ),
            {
                'DESCRIPTOR': _MDICT_DICTVALUEENTRY,
                '__module__': 'gRPC_comm_manager_pb2'
                # @@protoc_insertion_point(class_scope:mDict.DictValueEntry)
            }),
        'DESCRIPTOR': _MDICT,
        '__module__': 'gRPC_comm_manager_pb2'
        # @@protoc_insertion_point(class_scope:mDict)
    })
_sym_db.RegisterMessage(mDict)
_sym_db.RegisterMessage(mDict.DictValueEntry)

MessageResponse = _reflection.GeneratedProtocolMessageType(
    'MessageResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _MESSAGERESPONSE,
        '__module__': 'gRPC_comm_manager_pb2'
        # @@protoc_insertion_point(class_scope:MessageResponse)
    })
_sym_db.RegisterMessage(MessageResponse)

_GRPCCOMSERVEFUNC = DESCRIPTOR.services_by_name['gRPCComServeFunc']
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _MESSAGEREQUEST_MSGENTRY._options = None
    _MESSAGEREQUEST_MSGENTRY._serialized_options = b'8\001'
    _MDICT_DICTVALUEENTRY._options = None
    _MDICT_DICTVALUEENTRY._serialized_options = b'8\001'
    _MESSAGEREQUEST._serialized_start = 27
    _MESSAGEREQUEST._serialized_end = 137
    _MESSAGEREQUEST_MSGENTRY._serialized_start = 84
    _MESSAGEREQUEST_MSGENTRY._serialized_end = 137
    _MSGVALUE._serialized_start = 139
    _MSGVALUE._serialized_end = 245
    _MSINGLE._serialized_start = 247
    _MSINGLE._serialized_end = 329
    _MLIST._serialized_start = 331
    _MLIST._serialized_end = 369
    _MDICT._serialized_start = 371
    _MDICT._serialized_end = 482
    _MDICT_DICTVALUEENTRY._serialized_start = 423
    _MDICT_DICTVALUEENTRY._serialized_end = 482
    _MESSAGERESPONSE._serialized_start = 484
    _MESSAGERESPONSE._serialized_end = 514
    _GRPCCOMSERVEFUNC._serialized_start = 516
    _GRPCCOMSERVEFUNC._serialized_end = 584
# @@protoc_insertion_point(module_scope)
