use_gpu: True
device: 0
<<<<<<< HEAD
early_stopping: 100
federate:
  mode: 'standalone'
  make_global_eval: False
  local_update_steps: 100
=======
early_stop:
  patience: 20
  improve_indicator_mode: mean
federate:
  mode: 'standalone'
  make_global_eval: False
  local_update_steps: 1
>>>>>>> be synchronized with gitlab
  total_round_num: 400
  share_local_model: False
data:
  root: data/
<<<<<<< HEAD
  type: graph_multi_domain_mix
=======
  type: graph_multi_domain_mol
>>>>>>> be synchronized with gitlab
  pre_transforms: constant_feat
model:
  type: gin
  hidden: 64
  out_channels: 0
  task: graph
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf']   # to handle size-different pre & post layers
  # local_param: [ 'encoder_atom', 'encoder', 'clf', 'norms' ]  # pre, post + FedBN
optimizer:
  lr: 0.5
  weight_decay: 0.0005
  type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: graphminibatch_trainer
eval:
  freq: 5
  metrics: ['acc', 'correct']
