use_gpu: True
device: 2
<<<<<<< HEAD
early_stopping: 200
=======
early_stop:
  patience: 200
  improve_indicator_mode: mean
>>>>>>> be synchronized with gitlab
monitoring: ['dissim']
federate:
  mode: standalone
  local_update_steps: 2
  total_round_num: 400
data:
  root: data/
  type: 'csbm'
  #type: 'csbm_data_feb_05_2022-19:23'
  cSBM_phi: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
model:
  type: gpr
  hidden: 256
  out_channels: 2
personalization:
  local_param: ['prop1']
optimizer:
  lr: 0.5
  weight_decay: 0.0005
  type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodeminibatch_trainer
  finetune:
    steps: 2
    stepsize: 0.25
eval:
  metrics: ['acc', 'correct']
