use_gpu: True
device: 0
early_stop:
  patience: 100
  improve_indicator_mode: mean
federate:
  mode: standalone
  make_global_eval: True
  client_num: 5
  total_round_num: 400
data:
  root: data/
  type: cora
  splitter: 'louvain'
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
train:
  local_update_steps: 4
  optimizer:
    lr: 0.25
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  metrics: ['acc', 'correct']
