use_gpu: True
device: 2
early_stop:
  patience: 200
  improve_indicator_mode: mean
# monitoring: ['dissim']
federate:
  mode: standalone
  total_round_num: 400
data:
  root: data/
  type: 'csbm'
  #type: 'csbm_data_feb_07_2022-00:19'
  cSBM_phi: [0.1, 0.5, 0.9]
  batch_size: 1
model:
  type: gpr
  hidden: 256
  out_channels: 2
#personalization:
  #local_param: ['prop1']
train:
  local_update_steps: 2
  optimizer:
    lr: 0.5
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  metrics: ['acc', 'correct']
