use_gpu: True
device: 0
early_stop:
  patience: 20
  improve_indicator_mode: mean
federate:
  mode: standalone
  method: local
  make_global_eval: False
  total_round_num: 10
  share_local_model: False
data:
  batch_size: 64
  root: data/
  type: cikmcup
dataloader:
  type: pyg
model:
  type: gin
  hidden: 64
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf']
train:
  batch_or_epoch: epoch
  local_update_steps: 21
  optimizer:
    weight_decay: 0.0005
    type: SGD
trainer:
  type: graphminibatch_trainer
eval:
  freq: 5
  report: ['avg']
  best_res_update_round_wise_key: val_loss
  count_flops: False
