use_gpu: True
device: 0
early_stop:
  patience: 100
  improve_indicator_mode: mean
federate:
  make_global_eval: True
  local_update_steps: 1000000
  client_num: 5
  total_round_num: 400
  mode: 'standalone_local'
  standalone: 'local'
data:
  root: data/
  type: cora
  splitter: 'louvain'
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
optimizer:
  lr: 0.05
  weight_decay: 0.0005
  type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: graphfullbatch
