use_gpu: True
device: 2
federate:
  mode: standalone
  total_round_num: 300
  client_num: 5
  share_local_model: True
  online_aggr: True
  sample_client_rate: 1.0
  method: fedgc
  save_to: 'FedGC_on_Cifar4CL_lda0.5_lr0.05_lus5b_rn300.ckpt'
data:
  root: 'data'
  type: 'Cifar4CL'
  batch_size: 256
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]
  num_workers: 4
model:
  type: 'SimCLR'
train:
  local_update_steps: 5
  batch_or_epoch: 'batch'
  optimizer:
    lr: 0.01
    momentum: 0.1
early_stop:
  patience: 0
criterion:
  type: 'NT_xentloss'
trainer:
  type: 'cltrainer'
eval:
  freq: 2
  metrics: ['loss']
  split: ['val', 'test']