use_gpu: True
device: 2
federate:
  mode: standalone
  total_round_num: 100
  client_num: 5
  sample_client_rate: 1.0
  method: FedAvg
  save_to: '../SimCLR_on_Cifar4CL_global_lr0.03_lus10_rn100epoch_repairsave.ckpt'
data:
  root: 'data'
  type: 'Cifar4CL'
  batch_size: 512
  splitter: 'lda'
  splitter_args: [{'alpha': 0.1}]
  num_workers: 4
model:
  type: 'SimCLR'
train:
  local_update_steps: 10
  batch_or_epoch: 'epoch'
  optimizer:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0001
early_stop:
  patience: 0
criterion:
  type: 'NT_xentloss'
trainer:
  type: 'cltrainer'
eval:
  freq: 5
  metrics: ['loss']
  split: ['val', 'test']