use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 12345
federate:
  client_num: 3
  mode: 'distributed'
  make_global_eval: False
  online_aggr: False
  total_round_num: 20
distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  client_host: '127.0.0.1'
  client_port: 50053
  role: 'client'
  data_idx: 3
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
dataloader:
  batch_size: 10
model:
  type: convnet2
  hidden: 128
  out_channels: 62
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
  report: [ 'weighted_avg', 'raw' ]
  count_flops: False