use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 8
  total_round_num: 500
  save_to: "llama_dolly_fed_ot.ckpt"
  save_freq: -1
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'dolly-15k@llm'
  splits: [0.99, 0.0, 0.01]
  splitter: 'meta'
llm:
  tok_len: 650
  chat:
    max_len: 1000
  adapter:
    mv_to_cpu: True
  offsite_tuning:
    use: True
    eval_type: 'emu'
    kwargs: [ { "drop_ratio": 0.2 } ]
    emu_l: 2
    emu_r: 30
    emu_align:
      use: True
      restore_from: 'aligned_llama_dolly_fed_ot.ckpt'
      save_to: 'aligned_llama_dolly_fed_ot.ckpt'
      train:
        local_update_steps: '500'
        batch_or_epoch: 'batch'
        lm_loss_weight: 0.1
        kd_loss_weight: 0.9
        optimizer:
          lr: 0.01
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.005
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 50
  metrics: ['loss']
  split: ['test']
  best_res_update_round_wise_key: test_loss
  count_flops: False