use_gpu: True
device: 3
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  make_global_eval: True
  client_num: 5
  total_round_num: 500
  share_local_model: True
  online_aggr: True
  use_diff: True
data:
  root: data/
  type: cora
  splitter: 'louvain'
dataloader:
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
train:
  local_update_steps: 1
  optimizer:
    lr: 0.25
    weight_decay: 0.0005
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  freq: 1
  metrics: ['acc', 'correct', 'f1']
  split: ['test', 'val', 'train']
hpo:
  scheduler: wrap_sha
  num_workers: 0
  init_cand_num: 81
  ss: 'scripts/example_configs/cora/hpo_ss_fedex_arm_table.yaml'
  table:
    ss: 'scripts/example_configs/cora/hpo_ss_fedex_arm.yaml'
    num: 4
    cand: 81
  sha:
    budgets: [2, 4, 12, 36]
  fedex:
    use: True
    diff: False
    eta0: 0.050
    gamma: 0.495861
  metric: 'server_global_eval.val_avg_loss'
