use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: lr
data:
  root: data/
  type: credit
  batch_size: 2000
  splits: [0.8, 0.2]
dataloader:
  type: raw
criterion:
  type: CrossEntropyLoss
trainer:
  type: none    
train:
  optimizer:
    bin_num: 100
    lambda_: 0.1
    gamma: 0
    num_of_trees: 5
    max_tree_depth: 3
xgb_gh:
  use: True
  use_bin: True
  use_encryption: True
  key_size: 256
  dims: [5, 10]
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss