use_gpu: True
device: 4
outdir: exp/fedex_femnist_eval
seed: 12345
early_stop:
  patience: 100000
federate:
  mode: standalone
  client_num: 10
  total_round_num: 800
  sample_client_rate: 1.0
  share_local_model: True
  online_aggr: True
  use_diff: True
fedopt:
  use: True
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 10
  subsample: 0.05
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct']

