client_1:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.01
  federate:
    local_update_steps: 4
#  trainer:
#    finetune:
#      steps: 35
#      steps: 18
client_2:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 2
#  trainer:
#    finetune:
#      steps: 20
#      steps: 10
client_3:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 14
#  trainer:
#    finetune:
#      steps: 131
#      steps: 66
client_4:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.01
  federate:
    local_update_steps: 5
#  trainer:
#    finetune:
#      steps: 47
#      steps: 24
client_5:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.025
  federate:
    local_update_steps: 7
#  trainer:
#    finetune:
#      steps: 64
#      steps: 32
client_6:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.025
  federate:
    local_update_steps: 8
#  trainer:
#    finetune:
#      steps: 46
#      steps: 36
client_7:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 1
#  trainer:
#    finetune:
#      steps: 6
#      steps: 3
client_8:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.0001
  federate:
    local_update_steps: 1
#  trainer:
#    finetune:
#      steps: 11
#      steps: 5
client_9:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 1
#  trainer:
#    finetune:
#      steps: 10
#      steps: 5
client_10:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 1
#  trainer:
#    finetune:
#      steps: 11
#      steps: 5
client_11:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 5
#  trainer:
#    finetune:
#      steps: 11
#      steps: 22
client_12:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 14
#  trainer:
#    finetune:
#      steps: 129
#      steps: 64
client_13:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 14
#  trainer:
#    finetune:
#      steps: 128
#      steps: 64
client_14:
  model:
    out_channels: 12
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 675
#  trainer:
#    finetune:
#      steps: 6331
#      steps: 3165
client_15:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.1
  federate:
    local_update_steps: 832
#  trainer:
#    finetune:
#      steps: 7796
#      steps: 3898
client_16:
  model:
    out_channels: 19
    task: graphRegression
  criterion:
    type: MSELoss
  optimizer:
    lr: 0.05
  federate:
    local_update_steps: 431
#  trainer:
#    finetune:
#      steps: 4045
#      steps: 2022