use_gpu: True
device: 1
outdir: exp/fedex_cifar_eval
seed: 12345
early_stop:
  patience: 100000
federate:
  mode: standalone
  client_num: 10
  total_round_num: 800
  sample_client_rate: 1.0
  share_local_model: True
  online_aggr: True
  use_diff: True
data:
  root: data/
  type: 'CIFAR10@torchvision'
  subsample: 0.05
  splits: [ 0.8,0.2,0.0 ]
  batch_size: 32
  num_workers: 0
  transform: [ [ 'ToTensor' ], [ 'Normalize', { 'mean': [ 0.1307 ], 'std': [ 0.3081 ] } ] ]
  args: [ { 'download': True } ]
  splitter: 'lda'
  splitter_args: [ { 'alpha': 1.0 } ]
model:
  type: convnet2
  hidden: 128
  out_channels: 10
  dropout: 0.4360121205373164
train:
  batch_or_epoch: epoch
  local_update_steps: 4
  optimizer:
    type: SGD
    lr: 0.01
    weight_decay: 0.011880537011740954
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct']

