use_gpu: True
device: -1
early_stop:
  patience: 5
seed: 1
federate:
  mode: standalone
  local_update_steps: 1
  batch_or_epoch: epoch
  total_round_num: 1000
  sample_client_rate: 0.2
  unseen_clients_rate: 0.2
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 32
  subsample: 0.05
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  dropout: 0.0
optimizer:
  lr: 0.01
  weight_decay: 0.0
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
