use_gpu: True
device: 0
early_stop_patience: 5
seed: 2
federate:
  mode: standalone
  local_update_steps: 1
  batch_or_epoch: epoch
  total_round_num: 300
  sample_client_rate: 0.2
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 64
  subsample: 0.05
  num_workers: 0
  transform: 'transforms.ToTensor(), transforms.Normalize(mean=[0.1307], std=[0.3081])'
model:
  model_num_per_trainer: 3
  type: convnet2
  hidden: 2048
  out_channels: 62
personalization:
  local_update_steps: 1
  lr: 0.5
optimizer:
  lr: 0.5
  weight_decay: 0.0
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
