use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 6
  client_idx_for_local_train: 1
  total_round_num: 500
  save_to: "llama_csn_c1_30*500.ckpt"
  save_freq: 100
data:
  root: data/
  type: 'code_search_net@llm'
  splits: [0.998,0.001,0.001]
  splitter: 'meta'
  subsample: 0.05
llm:
  tok_len: 650
  chat:
    max_len: 1000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.001
    weight_decay: 0.0
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 50
  metrics: ['loss']