use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  client_idx: 2
  total_round_num: 500
  save_to: "llama_dolly_c2_30*500.ckpt"
  save_freq: 100
  share_local_model: False
  online_aggr: False
data:
  root: data/
  type: 'dolly-15k@llm'
  splits: [0.998,0.001,0.001]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]
llm:
  tok_len: 1000
  chat:
    max_len: 1000
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.00002
  is_enable_half: True
grad:
  grad_clip: 5
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 50
  metrics: ['loss']