use_gpu: True
device: 3
outdir: bo_kde_wrap_femnist_avg
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  total_round_num: 500
  sample_client_rate: 1.0
  share_local_model: True
  online_aggr: True
  use_diff: True
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
dataloader:
  batch_size: 16
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  dropout: 0.5
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct', 'f1']
  split: ['test', 'val', 'train']
hpo:
  scheduler: wrap_bo_kde
  num_workers: 0
  init_cand_num: 100
  ss: 'scripts/example_configs/femnist/avg/ss.yaml'
  sha:
    budgets: [ 50, 50 ]
    elim_rate: 3
    iter: 50
  table:
    num: 27
  fedex:
    sched: 'aggressive'
    use: True
    diff: False
    eta0: -1.0
    gamma: 0.0
  metric: 'client_summarized_weighted_avg.val_avg_loss'
  working_folder: bo_kde_wrap_femnist_avg
