use_gpu: True
device: 0
expname: 'tianchi_submit'
outdir: '.'
verbose: 1
early_stop:
  patience: 5
seed: 12345
federate:
  mode: standalone
  total_round_num: 100
  sample_client_rate: 0.1
  share_local_model: True
  online_aggr: True
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
dataloader:
  batch_size: 10
model:
  type: convnet2
  hidden: 128
  out_channels: 62
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
