use_gpu: True
device: 3
outdir: bohb_wrap_femnist_avg_robust
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  total_round_num: 500
  sample_client_rate: 1.0
  share_local_model: True
  online_aggr: True
  use_diff: True
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
dataloader:
  batch_size: 16
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  dropout: 0.5
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct', 'f1']
  split: ['test', 'val', 'train']
hpo:
  scheduler: wrap_bohb
  num_workers: 0
  ss: 'scripts/hpo_exp_scripts/robustness/attack/ss.yaml'
  sha:
    budgets: [ 9, 81 ]
    elim_rate: 3
    iter: 12
  fedex:
    sched: 'aggressive'
    use: True
    diff: False
    eta0: -1.0
    gamma: 0.0
    attack:
      id: [ 1 ]
      sigma: 1.0
  metric: 'client_summarized_weighted_avg.val_avg_loss'
  working_folder: bohb_wrap_femnist_avg_robust
