use_gpu: True
device: -1
early_stop:
  patience: 5
federate:
  mode: standalone
  client_num: 1000
  total_round_num: 1000
  local_update_steps: 1
  batch_or_epoch: epoch
  sample_client_rate: 0.2
  unseen_clients_rate: 0.2
data:
  root: data/
  type: VFLMovieLens10M
  batch_size: 1024
  num_workers: 0
  splits: [0.7,0.15,0.15]
model:
  type: VMFNet
  hidden: 20
optimizer:
  lr: 1.
  grad_clip: 5.0
criterion:
  type: MSELoss
trainer:
  type: mftrainer
eval:
  freq: 10
  best_res_update_round_wise_key: val_avg_loss
  task_type: regression