use_gpu: True
device: 0
seed: 12345
outdir: exp/
federate:
  mode: standalone
  method: fedavg
  total_round_num: 100
  client_num: 18
  atc_vanilla: True
data:
  type: atc_data
  root: datasets/
  datasets: ['imdb', 'agnews', 'squad', 'newsqa', 'cnndm', 'msqg']
  num_grouped_clients: [1, 3, 3, 2, 5, 4]
  num_workers: 0
  cache_dir: cache/
model:
  type: atc_model
  model_type: google/bert_uncased_L-2_H-128_A-2
personalization:
  local_param: ['classifier', 'encoder.pooler', 'decoder']
trainer:
  type: atc_trainer
train:
  batch_or_epoch: batch
  optimizer:
    type: AdamW
    lr: 5e-4
    weight_decay: 0.01
  scheduler:
    type: step
    warmup_ratio: 0.1
grad:
  grad_clip: 1.0
eval:
  split: ['test']
  report: ['group_avg']
  freq: 100000000  # eval freq across rounds
