TBD: http://11.158.195.242:8080/daoyuan/pfl_benchmark/runs/1elxhon7?workspace=user-daoyuan

use_gpu: True
device: 0
seed: 1
federate:
  mode: standalone
  total_round_num: 1000
  sample_client_rate: 0.2
data:
  root: data/
  type: shakespeare
  batch_size: 64
  subsample: 0.2
  num_workers: 0
  splits: [0.6,0.2,0.2]
model:
  type: lstm
  in_channels: 80
  out_channels: 80
  embed_size: 8
  hidden: 256
personalization:
  K: 3
  beta: 1.0
  local_param: []
  local_update_steps: 3
  lr: 0.8
  regular_weight: 1.0
  share_non_trainable_para: false
train:
  batch_or_epoch: epoch
  local_update_steps: 3
  optimizer:
    lr: 0.8
    weight_decay: 0.0
criterion:
  type: character_loss
trainer:
  type: nlptrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
