use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: xgb_tree
  lambda_: 0.1
  gamma: 0
  num_of_trees: 10
  max_tree_depth: 3
data:
  root: data/
  type: abalone
  splits: [0.8, 0.2]
dataloader:
  type: raw
  batch_size: 4000
criterion:
  type: Regression
trainer:
  type: verticaltrainer
train:
  optimizer:
    bin_num: 1000
    # learning rate for xgb model
    eta: 0.5
vertical:
  use: True
  dims: [4, 8]
  algo: 'xgb'
  xgb_use_bin: True
eval:
  freq: 5
  best_res_update_round_wise_key: test_loss