use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: lr
data:
  root: data/
  type: blog
  splits: [1.0, 0.0]
dataloader:
  type: raw
  batch_size: 8000
criterion:
  type: Regression
trainer:
  type: none
train:
  optimizer:
    bin_num: 1000
    lambda_: 10
    gamma: 0
    num_of_trees: 9
    max_tree_depth: 3
    # learning rate for xgb model
    eta: 1
vertical:
  use: True
  dims: [10, 20]
  algo: 'xgb'
  xgb_use_bin: True
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss