use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: lr
data:
  root: data/
  type: credit
  splits: [0.8, 0.2]
dataloader:
  type: raw
  batch_size: 2000
criterion:
  type: CrossEntropyLoss
trainer:
  type: none    
train:
  optimizer:
    bin_num: 100
    lambda_: 0.1
    gamma: 0
    num_of_trees: 10
    max_tree_depth: 3
    # learning rate for xgb model
    eta: 0.5
vertical:
  dims: [5, 10]
  algo: 'xgb'
  xgb_use_bin: True
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss