use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: lr
data:
  root: data/
  type: blog
  splits: [1.0, 0.0]
dataloader:
  type: raw
  batch_size: 8000
criterion:
  type: Regression
trainer:
  type: none
train:
  optimizer:
    bin_num: 1000
    lambda_: 10
    gamma: 0
    num_of_trees: 5
    max_tree_depth: 3
vertical_dims: [10, 20]
xgb_base:
  use: True
  use_bin: False
opboost_noise:
  use: True
  # op_algo: 'global' or 'adj'
  algo: 'adj'
  #the following is used for global
  epsilon: 2
  # the following are used for adj
  epsilon_prt: 2
  epsilon_ner: 2
  partition_num: 10
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss