use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 1
federate:
  mode: standalone
  total_round_num: 300
  sample_client_rate: 0.2
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
personalization:
  local_param: [ 'bn', 'norms' ]  # FedBN
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    lr: 0.1
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
