# deepspeed federatedscope/main.py --cfg federatedscope/llm/baseline/deepspeed/llama_ds.yaml
use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 1
  total_round_num: 500
  save_to: "llama_ds.ckpt"
data:
  root: data/
  type: 'alpaca@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 2000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 32, 'lora_dropout': 0.1 } ]
  deepspeed:
    use: True
    ds_config: 'federatedscope/llm/baseline/deepspeed/ds_config.json'
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-13b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.0003
    weight_decay: 0.0
  is_enable_half: True
trainer:
  type: llmtrainer
eval:
  freq: 5
  metrics: ['loss']
  count_flops: False