use_gpu: True
device: 0
outdir: cifar_exp/pfedhpo
seed: 12345
early_stop:
  patience: 100000
  improve_indicator_mode: mean
federate:
  mode: 'standalone'
  client_num: 10
  total_round_num: 4000
  sample_client_rate: 1.0
  share_local_model: True
  online_aggr: True
  use_diff: True
data:
  root: data/
  type: 'CIFAR10@torchvision'
  splits: [ 0.8,0.2,0.0 ]
  batch_size: 32
  num_workers: 0
  transform: [ [ 'ToTensor' ], [ 'Normalize', { 'mean': [ 0.1307 ], 'std': [ 0.3081 ] } ] ]
  args: [ { 'download': True } ]
  splitter: 'lda'
  splitter_args: [ { 'alpha': 1.0 } ]
model:
  type: convnet2
  hidden: 128
  out_channels: 10
  dropout: 0.0
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    type: SGD
    lr: 0.1
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: ['acc', 'correct']
  count_flops: False
hpo:
  scheduler: pfedhpo
  num_workers: 0
  pfedhpo:
    use: True
    discrete: True
    train_fl: False
    train_anchor: False
    target_fl_total_round: 400
    ss: 'scripts/example_configs/pfedhpo/cifar/ss.yaml'
  metric: 'client_summarized_weighted_avg.val_avg_loss'
  working_folder: cifar_exp/pfedhpo/working
