use_gpu: False
federate:
  mode: standalone
  client_num: 2
  total_round_num: 30
model:
  type: lr
  use_bias: False
train:
  optimizer:
    lr: 0.05
data:
  type: synthetic_vfl_data
dataloader:
  type: raw
  batch_size: 50
vertical:
  use: True
  key_size: 256
  algo: 'lr'
trainer:
  type: none
eval:
  freq: 5
  best_res_update_round_wise_key: test_loss
