use_gpu: True
device: 0
early_stop:
  patience: 100
federate:
  mode: standalone
  total_round_num: 100
  client_num: 480189
  online_aggr: True
  share_local_model: True
  sample_client_rate: 0.0001
data:
  root: data/
  type: HFLNetflix
dataloader:
  type: mf
model:
  type: HMFNet
  hidden: 10
train:
  local_update_steps: 50
  optimizer:
    lr: 1.
criterion:
  type: MSELoss
trainer:
  type: mftrainer
eval:
  freq: 100
  metrics: []
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False