use_gpu: True
device: 0
early_stop:
  patience: 100
federate:
  mode: standalone
  total_round_num: 100
  client_num: 5
data:
  root: data/
  type: HFLMovieLens1M
dataloader:
  type: mf
model:
  type: HMFNet
  hidden: 20
train:
  local_update_steps: 50
  optimizer:
    lr: 1.
criterion:
  type: MSELoss
trainer:
  type: mftrainer
eval:
  freq: 100
  metrics: []
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False