use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: lr
data:
  root: data/
  type: blog
  batch_size: 8000
  splits: [1.0, 0.0]
dataloader:
  type: raw
criterion:
  type: Regression
trainer:
  type: none
train:
  optimizer:
    learning_rate: 0.1
    bin_num: 1000
    lambda_: 10
    gamma: 0
    num_of_trees: 5
    max_tree_depth: 3
gbdt:
  use: True
  use_bin: False
  dims: [10, 20]
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss