use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: lr
data:
  root: data/
  type: abalone
  batch_size: 4000
  splits: [0.8, 0.2]
dataloader:
  type: raw
criterion:
  type: Regression
trainer:
  type: none    
train:
  optimizer:
    learning_rate: 0.1
    bin_num: 1000
    lambda_: 0.1
    gamma: 0
    num_of_trees: 5
    max_tree_depth: 3
vertical_dims: [4, 8]
gbdt:
  use: True
  use_bin: True
eval:
  freq: 5
  best_res_update_round_wise_key: test_loss