use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 9
  total_round_num: 500
  save_to: "llama_rosetta_9_fed_30*500_0.003_32_0.1.ckpt"
  save_freq: -1
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'rosetta_alpaca@llm'
  splits: [0.89,0.1,0.01]
  splitter: 'meta'
llm:
  tok_len: 650
  chat:
    max_len: 1000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 32, 'lora_dropout': 0.0 } ]
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.0001
    weight_decay: 0.0
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 50
  metrics: ['loss']
  best_res_update_round_wise_key: val_loss
  count_flops: False