use_gpu: False
federate:
  mode: standalone
  client_num: 2
  total_round_num: 50
model:
  type: nn
  use_bias: False
train:
  optimizer:
    lr: 0.7
data:
  root: data/
  type: synthetic_vfl_data
  args: [{normalization: False, standardization: False}]
criterion:
  type: CrossEntropyLoss
dataloader:
  type: raw
  batch_size: 50
vertical:
  use: True
  dims: [5, 10]
  output_layer: [2, 2]
  key_size: 256
  algo: 'nn'
  protect_method: 'dp'
  protect_args: [{'algo': 'Laplace', 'para': 0.01}]   # [{'algo': 'Bernoulli', 'para': 0}]
trainer:
  type: nntrainer
eval:
  freq: 5
  best_res_update_round_wise_key: test_loss
