use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 500
  save_to: "code_mezo_lda.ckpt"
  save_freq: 100
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'rosetta_alpaca@llm'
  splits: [0.99,0.00,0.01]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]
llm:
  tok_len: 650
  chat:
    max_len: 1000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 128, 'lora_alpha': 256, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 1
model:
  type: 'openlm-research/open_llama_3b_v2@huggingface_llm'
train:
  train_strategy: 'frozen'
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.00002
    weight_decay: 0.0
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: mezotrainer
eval:
  freq: 10
  metrics: ['loss']
  split: ['test']
  best_res_update_round_wise_key: test_loss
  count_flops: False