use_gpu: True
device: 0
early_stop:
  patience: 10
federate:
  mode: standalone
  client_num: 1
  total_round_num: 200
  save_to: "gpt2.ckpt"
  share_local_model: False
  online_aggr: False
data:
  root: data/
  type: 'dolly-15k@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.05}]
llm:
  tok_len: 1000
  chat:
    max_len: 1000
dataloader:
  batch_size: 1
model:
  type: 'gpt2@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 10
  metrics: ['loss']