use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 100
  save_to: "mezo_testcase.ckpt"
  save_freq: 50
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'alpaca@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 2000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 1
model:
  type: 'openlm-research/open_llama_3b_v2@huggingface_llm'
train:
  train_strategy: 'frozen'
  local_update_steps: 5
  batch_or_epoch: batch
  optimizer:
    lr: 0.00001
    weight_decay: 0.0
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: mezotrainer
eval:
  freq: 10
  metrics: ['loss']
  count_flops: False