use_gpu: True
device: 0
early_stop:
  patience: 10
federate:
  mode: standalone
  client_num: 1
  total_round_num: 200
  save_to: "gpt2_new.ckpt"
  share_local_model: False
  online_aggr: False
data:
  root: data/
  type: 'alpaca_data.json@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 1000
  accelerator:
    use: True
dataloader:
  batch_size: 1
model:
  type: 'gpt2@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 0.001
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 50
  metrics: ['loss']